// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2 — DATABANK SCHEMATIC & SEED MOCKING
// 55 realistic Qatar real estate records spanning Doha, The Pearl,
// West Bay, Lusail, Al Sadd, Al Waab, Msheireb, Al Dafna & Madinat Khalifa.
// ─────────────────────────────────────────────────────────────────────────────

import {
  UnitListing,
  Status,
  Furnishing,
  ListingType,
  UnitType,
  SubType,
} from '../types/inventory';

export const mockUnits: UnitListing[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: WEST BAY — 10 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-001',
    realtorMOCI: 'PRV-MOCI-2024-0101',
    property: 'Tornado Tower Residences',
    unitNo: 'TT-14-02A',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 12500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Tornado+Tower+West+Bay+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-001-tornado-14-02a',
    serviceCharges: 950,
    depositAmount: 25000,
    agencyFee: 7500,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0101',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'AC units serviced Q3 2024. Plumbing checked and cleared. No active maintenance tickets.',
    accessLockbox: 'Code: 4821 — Floor 14, Door Right',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-001-v1', 'https://drive.google.com/file/d/prv-hist-001-v2'],
    listedDate: '2024-09-01',
    lastUpdated: '2024-11-15',
  },
  {
    id: 'PRV-002',
    realtorMOCI: 'PRV-MOCI-2024-0102',
    property: 'Tornado Tower Residences',
    unitNo: 'TT-22-04B',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 16500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Tornado+Tower+West+Bay+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-002-tornado-22-04b',
    serviceCharges: 1200,
    depositAmount: 33000,
    agencyFee: 9900,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0102',
    legalDuration: '2 Years',
    maintenanceNotes: 'Unit fully inspected pre-lease. All fixtures and appliances in working order per handover report.',
    accessLockbox: 'Code: 7753 — Floor 22, Suite B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-002-v1'],
    listedDate: '2024-07-15',
    lastUpdated: '2024-10-01',
  },
  {
    id: 'PRV-003',
    realtorMOCI: 'PRV-MOCI-2024-0103',
    property: 'Al Fardan Pearl Tower',
    unitNo: 'FP-08-01C',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 8200,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Al+Fardan+Pearl+Tower+West+Bay+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-003-fardan-08-01c',
    serviceCharges: 620,
    depositAmount: 16400,
    agencyFee: 4920,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0103',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Kitchen appliances replaced Q2 2024. Bathroom retiled. No open work orders.',
    accessLockbox: 'Code: 3318 — Level 8, West Wing',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-003-v1'],
    listedDate: '2024-10-10',
    lastUpdated: '2024-11-20',
  },
  {
    id: 'PRV-004',
    realtorMOCI: 'PRV-MOCI-2024-0104',
    property: 'Al Fardan Pearl Tower',
    unitNo: 'FP-15-03D',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 13000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Fardan+Pearl+Tower+West+Bay+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-004-fardan-15-03d',
    serviceCharges: 980,
    depositAmount: 26000,
    agencyFee: 7800,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0104',
    legalDuration: '1 Year',
    maintenanceNotes: 'Tenant-reported AC issue resolved Nov 2024. All systems nominal.',
    accessLockbox: 'Code: 9124 — Level 15, East Wing',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-004-v1'],
    listedDate: '2024-06-20',
    lastUpdated: '2024-11-05',
  },
  {
    id: 'PRV-005',
    realtorMOCI: 'PRV-MOCI-2024-0105',
    property: 'Burj Al Marina',
    unitNo: 'BM-31-PH1',
    zone: 'West Bay',
    type: UnitType.Penthouse,
    subType: SubType.Penthouse,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 38000,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Burj+Al+Marina+West+Bay+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-005-burj-31-ph1',
    serviceCharges: 3200,
    depositAmount: 114000,
    agencyFee: 22800,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-WB-0105',
    legalDuration: '1 Year',
    maintenanceNotes: 'Private terrace irrigation system under inspection. Expected completion 5 Dec 2024.',
    accessLockbox: 'Code: 5501 — Penthouse Level, Private Lift',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-005-v1', 'https://drive.google.com/file/d/prv-hist-005-v2'],
    listedDate: '2024-08-01',
    lastUpdated: '2024-11-28',
  },
  {
    id: 'PRV-006',
    realtorMOCI: 'PRV-MOCI-2024-0106',
    property: 'Burj Al Marina',
    unitNo: 'BM-12-02B',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 14500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Burj+Al+Marina+West+Bay+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-006-burj-12-02b',
    serviceCharges: 1050,
    depositAmount: 29000,
    agencyFee: 8700,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0106',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Recently vacated and deep-cleaned. Fresh paint applied October 2024.',
    accessLockbox: 'Code: 6670 — Level 12, Block B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-006-v1'],
    listedDate: '2024-11-01',
    lastUpdated: '2024-11-25',
  },
  {
    id: 'PRV-007',
    realtorMOCI: 'PRV-MOCI-2024-0107',
    property: 'West Bay Lagoon Tower',
    unitNo: 'WBL-06-01A',
    zone: 'West Bay',
    type: UnitType.Studio,
    subType: SubType.Studio,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 5800,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=West+Bay+Lagoon+Tower+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-007-wbl-06-01a',
    serviceCharges: 380,
    depositAmount: 11600,
    agencyFee: 3480,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0107',
    legalDuration: '1 Year',
    maintenanceNotes: 'All appliances functional. Lease renewed Oct 2024.',
    accessLockbox: 'Code: 2245 — Level 6, Unit 1A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-007-v1'],
    listedDate: '2024-05-01',
    lastUpdated: '2024-10-15',
  },
  {
    id: 'PRV-008',
    realtorMOCI: 'PRV-MOCI-2024-0108',
    property: 'West Bay Lagoon Tower',
    unitNo: 'WBL-19-03B',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Unfurnished,
    listingType: ListingType.Rent,
    rent: 9000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=West+Bay+Lagoon+Tower+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-008-wbl-19-03b',
    serviceCharges: 650,
    depositAmount: 18000,
    agencyFee: 5400,
    agencyFeePercentage: 5,
    mociContractStatus: 'DRAFT',
    mociContractNumber: 'MOCI-2024-WB-0108',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Unit recently vacated. Carpet replacement scheduled for mid-December 2024.',
    accessLockbox: 'Code: 8832 — Level 19, Block B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-008-v1'],
    listedDate: '2024-11-10',
    lastUpdated: '2024-11-30',
  },
  {
    id: 'PRV-009',
    realtorMOCI: 'PRV-MOCI-2024-0109',
    property: 'Doha Corniche Plaza',
    unitNo: 'DCP-04-02C',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 11500,
    status: Status.Under_Maintenance,
    locationMapUrl: 'https://maps.google.com/?q=Doha+Corniche+Plaza+West+Bay+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-009-dcp-04-02c',
    serviceCharges: 870,
    depositAmount: 23000,
    agencyFee: 6900,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0109',
    legalDuration: '1 Year',
    maintenanceNotes: 'HVAC system overhaul in progress. Water pressure issue in master bath. ETA resolution: 15 Dec 2024.',
    accessLockbox: 'Code: 1197 — Level 4, Unit 2C (Contractor Access)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-009-v1'],
    listedDate: '2024-04-15',
    lastUpdated: '2024-11-28',
  },
  {
    id: 'PRV-010',
    realtorMOCI: 'PRV-MOCI-2024-0110',
    property: 'Doha Corniche Plaza',
    unitNo: 'DCP-27-01A',
    zone: 'West Bay',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 18000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Doha+Corniche+Plaza+West+Bay+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-010-dcp-27-01a',
    serviceCharges: 1350,
    depositAmount: 36000,
    agencyFee: 10800,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-WB-0110',
    legalDuration: '2 Years',
    maintenanceNotes: 'No open tickets. Tenant satisfied per last inspection report Sept 2024.',
    accessLockbox: 'Code: 4499 — Level 27, Penthouse Corridor',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-010-v1'],
    listedDate: '2024-03-10',
    lastUpdated: '2024-09-15',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: THE PEARL QATAR — 12 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-011',
    realtorMOCI: 'PRV-MOCI-2024-0201',
    property: 'Viva Bahriya Tower',
    unitNo: 'VB-07-03A',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 9500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Viva+Bahriya+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-011-viva-07-03a',
    serviceCharges: 720,
    depositAmount: 19000,
    agencyFee: 5700,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0201',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Freshly refurbished. New flooring installed October 2024. Move-in ready.',
    accessLockbox: 'Code: 3374 — Tower 7, Level 3',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-011-v1'],
    listedDate: '2024-10-20',
    lastUpdated: '2024-11-18',
  },
  {
    id: 'PRV-012',
    realtorMOCI: 'PRV-MOCI-2024-0202',
    property: 'Viva Bahriya Tower',
    unitNo: 'VB-23-07C',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 14000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Viva+Bahriya+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-012-viva-23-07c',
    serviceCharges: 1050,
    depositAmount: 28000,
    agencyFee: 8400,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0202',
    legalDuration: '1 Year',
    maintenanceNotes: 'Under active lease. Last inspection: Aug 2024 — all good.',
    accessLockbox: 'Code: 6681 — Tower 23, Level 7',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-012-v1'],
    listedDate: '2024-05-15',
    lastUpdated: '2024-09-01',
  },
  {
    id: 'PRV-013',
    realtorMOCI: 'PRV-MOCI-2024-0203',
    property: 'Porto Arabia Residences',
    unitNo: 'PA-14-05B',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 15500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Porto+Arabia+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-013-porto-14-05b',
    serviceCharges: 1150,
    depositAmount: 31000,
    agencyFee: 9300,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0203',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Sea-facing unit. Full balcony glazing cleaned Nov 2024. Appliances all under warranty.',
    accessLockbox: 'Code: 2250 — Porto Block 14, Floor 5',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-013-v1'],
    listedDate: '2024-10-05',
    lastUpdated: '2024-11-20',
  },
  {
    id: 'PRV-014',
    realtorMOCI: 'PRV-MOCI-2024-0204',
    property: 'Porto Arabia Residences',
    unitNo: 'PA-31-09A',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 22000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Porto+Arabia+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-014-porto-31-09a',
    serviceCharges: 1650,
    depositAmount: 44000,
    agencyFee: 13200,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0204',
    legalDuration: '2 Years',
    maintenanceNotes: 'Corporate tenant. No issues reported. Quarterly inspection scheduled Jan 2025.',
    accessLockbox: 'Code: 7744 — Porto Block 31, Floor 9',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-014-v1'],
    listedDate: '2024-02-20',
    lastUpdated: '2024-08-01',
  },
  {
    id: 'PRV-015',
    realtorMOCI: 'PRV-MOCI-2024-0205',
    property: 'Porto Arabia Penthouse Collection',
    unitNo: 'PA-PH-02',
    zone: 'The Pearl Qatar',
    type: UnitType.Penthouse,
    subType: SubType.Penthouse,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 42000,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Porto+Arabia+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-015-porto-ph-02',
    serviceCharges: 3800,
    depositAmount: 126000,
    agencyFee: 25200,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-PL-0205',
    legalDuration: '1 Year',
    maintenanceNotes: 'Private rooftop pool maintenance ongoing. Expected handover Dec 10, 2024.',
    accessLockbox: 'Code: 0012 — Penthouse Private Lift (PIN required)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-015-v1', 'https://drive.google.com/file/d/prv-hist-015-v2'],
    listedDate: '2024-09-15',
    lastUpdated: '2024-11-29',
  },
  {
    id: 'PRV-016',
    realtorMOCI: 'PRV-MOCI-2024-0206',
    property: 'Qanat Quartier Residences',
    unitNo: 'QQ-08-04B',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 13500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Qanat+Quartier+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-016-qanat-08-04b',
    serviceCharges: 1000,
    depositAmount: 27000,
    agencyFee: 8100,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0206',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Mediterranean-style canal-facing unit. No issues. Ready for viewing.',
    accessLockbox: 'Code: 5512 — Qanat Block 8, Level 4',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-016-v1'],
    listedDate: '2024-11-05',
    lastUpdated: '2024-11-25',
  },
  {
    id: 'PRV-017',
    realtorMOCI: 'PRV-MOCI-2024-0207',
    property: 'Qanat Quartier Residences',
    unitNo: 'QQ-18-08A',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 19500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Qanat+Quartier+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-017-qanat-18-08a',
    serviceCharges: 1480,
    depositAmount: 39000,
    agencyFee: 11700,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0207',
    legalDuration: '2 Years',
    maintenanceNotes: 'No active tickets. Tenant's renewal processed Sept 2024.',
    accessLockbox: 'Code: 8830 — Qanat Block 18, Level 8',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-017-v1'],
    listedDate: '2024-01-10',
    lastUpdated: '2024-09-20',
  },
  {
    id: 'PRV-018',
    realtorMOCI: 'PRV-MOCI-2024-0208',
    property: 'Medina Centrale Tower',
    unitNo: 'MC-12-06C',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 8800,
    status: Status.Under_Maintenance,
    locationMapUrl: 'https://maps.google.com/?q=Medina+Centrale+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-018-medina-12-06c',
    serviceCharges: 660,
    depositAmount: 17600,
    agencyFee: 5280,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0208',
    legalDuration: '1 Year',
    maintenanceNotes: 'Electrical rewiring of kitchen circuit in progress. Damp patch repair on exterior wall. ETA: 20 Dec 2024.',
    accessLockbox: 'Code: 1188 — Medina Block 12, Level 6 (Maintenance Access)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-018-v1'],
    listedDate: '2024-06-01',
    lastUpdated: '2024-11-27',
  },
  {
    id: 'PRV-019',
    realtorMOCI: 'PRV-MOCI-2024-0209',
    property: 'Medina Centrale Tower',
    unitNo: 'MC-25-10A',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 14800,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Medina+Centrale+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-019-medina-25-10a',
    serviceCharges: 1100,
    depositAmount: 29600,
    agencyFee: 8880,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0209',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Corner unit with panoramic views. Recently vacated, professionally cleaned. Ready.',
    accessLockbox: 'Code: 4422 — Medina Block 25, Level 10',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-019-v1'],
    listedDate: '2024-11-12',
    lastUpdated: '2024-11-30',
  },
  {
    id: 'PRV-020',
    realtorMOCI: 'PRV-MOCI-2024-0210',
    property: 'Pearl Marina View Suites',
    unitNo: 'PMV-03-01B',
    zone: 'The Pearl Qatar',
    type: UnitType.Studio,
    subType: SubType.Studio,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 6500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Pearl+Marina+View+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-020-pmv-03-01b',
    serviceCharges: 420,
    depositAmount: 13000,
    agencyFee: 3900,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0210',
    legalDuration: '1 Year',
    maintenanceNotes: 'Tenant reports minor water pressure drop — plumber scheduled Dec 2024.',
    accessLockbox: 'Code: 7700 — Block PMV-3, Ground Floor',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-020-v1'],
    listedDate: '2024-04-01',
    lastUpdated: '2024-10-20',
  },
  {
    id: 'PRV-021',
    realtorMOCI: 'PRV-MOCI-2024-0211',
    property: 'Pearl Marina View Suites',
    unitNo: 'PMV-16-05A',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 15000,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Pearl+Marina+View+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-021-pmv-16-05a',
    serviceCharges: 1120,
    depositAmount: 30000,
    agencyFee: 9000,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-PL-0211',
    legalDuration: '1 Year',
    maintenanceNotes: 'Unit held for incoming VIP tenant. Snagging checklist cleared Nov 20, 2024.',
    accessLockbox: 'Code: 9955 — Block PMV-16, Level 5',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-021-v1'],
    listedDate: '2024-10-30',
    lastUpdated: '2024-11-25',
  },
  {
    id: 'PRV-022',
    realtorMOCI: 'PRV-MOCI-2024-0212',
    property: 'Island Elegance Suites',
    unitNo: 'IE-09-04C',
    zone: 'The Pearl Qatar',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 21000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Island+Elegance+The+Pearl+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-022-ie-09-04c',
    serviceCharges: 1580,
    depositAmount: 42000,
    agencyFee: 12600,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-PL-0212',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'High-spec finishing. Smart home system fully operational. Ready for immediate occupation.',
    accessLockbox: 'Code: 3361 — Island Elegance Tower 9, Level 4',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-022-v1'],
    listedDate: '2024-11-08',
    lastUpdated: '2024-11-28',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: LUSAIL CITY — 9 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-023',
    realtorMOCI: 'PRV-MOCI-2024-0301',
    property: 'Marina Lusail Residences',
    unitNo: 'ML-11-03A',
    zone: 'Lusail City',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 11000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Marina+Lusail+Residences+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-023-ml-11-03a',
    serviceCharges: 820,
    depositAmount: 22000,
    agencyFee: 6600,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0301',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Marina-view unit. Newly handed over Q4 2024. No maintenance history yet.',
    accessLockbox: 'Code: 5523 — Marina Tower 11, Level 3',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-023-v1'],
    listedDate: '2024-10-25',
    lastUpdated: '2024-11-20',
  },
  {
    id: 'PRV-024',
    realtorMOCI: 'PRV-MOCI-2024-0302',
    property: 'Marina Lusail Residences',
    unitNo: 'ML-24-08B',
    zone: 'Lusail City',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 16000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Marina+Lusail+Residences+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-024-ml-24-08b',
    serviceCharges: 1200,
    depositAmount: 32000,
    agencyFee: 9600,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0302',
    legalDuration: '1 Year',
    maintenanceNotes: 'Occupied. Tenant raised AC efficiency concern in summer 2024 — resolved.',
    accessLockbox: 'Code: 8841 — Marina Tower 24, Level 8',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-024-v1'],
    listedDate: '2024-04-20',
    lastUpdated: '2024-10-10',
  },
  {
    id: 'PRV-025',
    realtorMOCI: 'PRV-MOCI-2024-0303',
    property: 'Fox Hills Compound',
    unitNo: 'FH-V-05',
    zone: 'Lusail City',
    type: UnitType.Villa,
    subType: SubType.Villa_4BR,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 28000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Fox+Hills+Compound+Lusail+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-025-fh-v05',
    serviceCharges: 2100,
    depositAmount: 84000,
    agencyFee: 16800,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0303',
    legalDuration: '2 Years',
    maintenanceNotes: 'Private garden landscaped Q3 2024. Pool servicing up to date. Smart security system installed.',
    accessLockbox: 'Code: 6677 — Fox Hills Gate 2, Villa 5',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-025-v1', 'https://drive.google.com/file/d/prv-hist-025-v2'],
    listedDate: '2024-10-01',
    lastUpdated: '2024-11-22',
  },
  {
    id: 'PRV-026',
    realtorMOCI: 'PRV-MOCI-2024-0304',
    property: 'Fox Hills Compound',
    unitNo: 'FH-V-12',
    zone: 'Lusail City',
    type: UnitType.Villa,
    subType: SubType.Villa_3BR,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 22000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Fox+Hills+Compound+Lusail+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-026-fh-v12',
    serviceCharges: 1650,
    depositAmount: 66000,
    agencyFee: 13200,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0304',
    legalDuration: '2 Years',
    maintenanceNotes: 'Under active lease. Tenant family occupying since Jan 2024. No issues.',
    accessLockbox: 'Code: 2290 — Fox Hills Gate 2, Villa 12',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-026-v1'],
    listedDate: '2024-01-15',
    lastUpdated: '2024-08-20',
  },
  {
    id: 'PRV-027',
    realtorMOCI: 'PRV-MOCI-2024-0305',
    property: 'Lusail Boulevard Tower',
    unitNo: 'LBT-16-05A',
    zone: 'Lusail City',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Unfurnished,
    listingType: ListingType.Rent,
    rent: 7500,
    status: Status.Under_Maintenance,
    locationMapUrl: 'https://maps.google.com/?q=Lusail+Boulevard+Tower+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-027-lbt-16-05a',
    serviceCharges: 560,
    depositAmount: 15000,
    agencyFee: 4500,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0305',
    legalDuration: '1 Year',
    maintenanceNotes: 'Balcony waterproofing under remediation. Internal repainting 70% complete. ETA handover: 8 Jan 2025.',
    accessLockbox: 'Code: 4455 — LBT Level 16, Unit 5A (Maintenance)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-027-v1'],
    listedDate: '2024-07-01',
    lastUpdated: '2024-11-29',
  },
  {
    id: 'PRV-028',
    realtorMOCI: 'PRV-MOCI-2024-0306',
    property: 'Lusail Boulevard Tower',
    unitNo: 'LBT-29-11C',
    zone: 'Lusail City',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 11500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Lusail+Boulevard+Tower+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-028-lbt-29-11c',
    serviceCharges: 860,
    depositAmount: 23000,
    agencyFee: 6900,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0306',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'High-floor unit with boulevard views. No open tickets.',
    accessLockbox: 'Code: 1134 — LBT Level 29, Suite 11C',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-028-v1'],
    listedDate: '2024-11-14',
    lastUpdated: '2024-11-29',
  },
  {
    id: 'PRV-029',
    realtorMOCI: 'PRV-MOCI-2024-0307',
    property: 'Al Erkyah City Residences',
    unitNo: 'AE-08-02B',
    zone: 'Lusail City',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 12000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Erkyah+City+Lusail+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-029-ae-08-02b',
    serviceCharges: 900,
    depositAmount: 24000,
    agencyFee: 7200,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0307',
    legalDuration: '1 Year',
    maintenanceNotes: 'Active lease. Tenant satisfied. No maintenance requests logged.',
    accessLockbox: 'Code: 8800 — Erkyah Block 8, Level 2',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-029-v1'],
    listedDate: '2024-03-05',
    lastUpdated: '2024-09-10',
  },
  {
    id: 'PRV-030',
    realtorMOCI: 'PRV-MOCI-2024-0308',
    property: 'Al Erkyah City Residences',
    unitNo: 'AE-17-06A',
    zone: 'Lusail City',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 17500,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Al+Erkyah+City+Lusail+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-030-ae-17-06a',
    serviceCharges: 1300,
    depositAmount: 35000,
    agencyFee: 10500,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-LS-0308',
    legalDuration: '2 Years',
    maintenanceNotes: 'Reserved for corporate relocation package. Pre-move inspection passed Nov 22.',
    accessLockbox: 'Code: 3390 — Erkyah Block 17, Level 6',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-030-v1'],
    listedDate: '2024-09-20',
    lastUpdated: '2024-11-25',
  },
  {
    id: 'PRV-031',
    realtorMOCI: 'PRV-MOCI-2024-0309',
    property: 'Lusail City Marina Walk',
    unitNo: 'LCM-05-01A',
    zone: 'Lusail City',
    type: UnitType.Studio,
    subType: SubType.Studio,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 5200,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Lusail+Marina+Walk+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-031-lcm-05-01a',
    serviceCharges: 360,
    depositAmount: 10400,
    agencyFee: 3120,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-LS-0309',
    legalDuration: '1 Year',
    maintenanceNotes: 'New build. First letting. All warranties active. No maintenance history.',
    accessLockbox: 'Code: 7723 — Marina Walk Tower 5, Ground Level',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-031-v1'],
    listedDate: '2024-11-01',
    lastUpdated: '2024-11-28',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: AL SADD — 7 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-032',
    realtorMOCI: 'PRV-MOCI-2024-0401',
    property: 'Al Sadd Executive Tower',
    unitNo: 'SET-12-03A',
    zone: 'Al Sadd',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 6800,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Al+Sadd+Executive+Tower+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-032-set-12-03a',
    serviceCharges: 520,
    depositAmount: 13600,
    agencyFee: 4080,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AS-0401',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Compact executive unit. Full repaint completed Nov 2024. Fridge replaced.',
    accessLockbox: 'Code: 2218 — SET Level 12, Unit 3A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-032-v1'],
    listedDate: '2024-11-05',
    lastUpdated: '2024-11-28',
  },
  {
    id: 'PRV-033',
    realtorMOCI: 'PRV-MOCI-2024-0402',
    property: 'Al Sadd Executive Tower',
    unitNo: 'SET-22-07B',
    zone: 'Al Sadd',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 9500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Sadd+Executive+Tower+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-033-set-22-07b',
    serviceCharges: 720,
    depositAmount: 19000,
    agencyFee: 5700,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AS-0402',
    legalDuration: '1 Year',
    maintenanceNotes: 'Tenant renewed for 2nd year. No outstanding issues.',
    accessLockbox: 'Code: 9912 — SET Level 22, Suite 7B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-033-v1'],
    listedDate: '2024-02-01',
    lastUpdated: '2024-10-05',
  },
  {
    id: 'PRV-034',
    realtorMOCI: 'PRV-MOCI-2024-0403',
    property: 'Regency Heights Al Sadd',
    unitNo: 'RH-09-04C',
    zone: 'Al Sadd',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Unfurnished,
    listingType: ListingType.Rent,
    rent: 8500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Regency+Heights+Al+Sadd+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-034-rh-09-04c',
    serviceCharges: 640,
    depositAmount: 17000,
    agencyFee: 5100,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AS-0403',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Spacious unfurnished unit. Viewing available daily 10am–6pm. No issues.',
    accessLockbox: 'Code: 6612 — Regency Level 9, Unit 4C',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-034-v1'],
    listedDate: '2024-10-28',
    lastUpdated: '2024-11-20',
  },
  {
    id: 'PRV-035',
    realtorMOCI: 'PRV-MOCI-2024-0404',
    property: 'Regency Heights Al Sadd',
    unitNo: 'RH-18-09A',
    zone: 'Al Sadd',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 13000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Regency+Heights+Al+Sadd+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-035-rh-18-09a',
    serviceCharges: 980,
    depositAmount: 26000,
    agencyFee: 7800,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AS-0404',
    legalDuration: '2 Years',
    maintenanceNotes: 'Family tenancy. Annual HVAC service completed Jul 2024. No active tickets.',
    accessLockbox: 'Code: 4450 — Regency Level 18, Penthouse Suite',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-035-v1'],
    listedDate: '2024-01-20',
    lastUpdated: '2024-08-15',
  },
  {
    id: 'PRV-036',
    realtorMOCI: 'PRV-MOCI-2024-0405',
    property: 'Al Sadd Plaza Residences',
    unitNo: 'SPR-04-02B',
    zone: 'Al Sadd',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 7200,
    status: Status.Under_Maintenance,
    locationMapUrl: 'https://maps.google.com/?q=Al+Sadd+Plaza+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-036-spr-04-02b',
    serviceCharges: 540,
    depositAmount: 14400,
    agencyFee: 4320,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AS-0405',
    legalDuration: '1 Year',
    maintenanceNotes: 'Post-tenancy snagging underway. Shower enclosure replacement and tile grout repair. ETA Dec 18, 2024.',
    accessLockbox: 'Code: 5588 — Plaza Level 4, Unit 2B (Maintenance)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-036-v1'],
    listedDate: '2024-05-10',
    lastUpdated: '2024-11-26',
  },
  {
    id: 'PRV-037',
    realtorMOCI: 'PRV-MOCI-2024-0406',
    property: 'Al Sadd Plaza Residences',
    unitNo: 'SPR-14-06A',
    zone: 'Al Sadd',
    type: UnitType.Studio,
    subType: SubType.Studio,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 4500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Sadd+Plaza+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-037-spr-14-06a',
    serviceCharges: 300,
    depositAmount: 9000,
    agencyFee: 2700,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AS-0406',
    legalDuration: '1 Year',
    maintenanceNotes: 'Student tenant. No issues. Lease ends Apr 2025.',
    accessLockbox: 'Code: 1101 — Plaza Level 14, Studio 6A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-037-v1'],
    listedDate: '2024-04-01',
    lastUpdated: '2024-09-15',
  },
  {
    id: 'PRV-038',
    realtorMOCI: 'PRV-MOCI-2024-0407',
    property: 'Najma Tower Al Sadd',
    unitNo: 'NTS-07-03C',
    zone: 'Al Sadd',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 9000,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Najma+Tower+Al+Sadd+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-038-nts-07-03c',
    serviceCharges: 680,
    depositAmount: 18000,
    agencyFee: 5400,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-AS-0407',
    legalDuration: '1 Year',
    maintenanceNotes: 'Reserved pending credit check approval. Unit is in excellent condition.',
    accessLockbox: 'Code: 7766 — Najma Level 7, Unit 3C',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-038-v1'],
    listedDate: '2024-11-15',
    lastUpdated: '2024-11-30',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: AL WAAB — 5 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-039',
    realtorMOCI: 'PRV-MOCI-2024-0501',
    property: 'Al Waab Garden Villas',
    unitNo: 'WGV-V03',
    zone: 'Al Waab',
    type: UnitType.Villa,
    subType: SubType.Villa_4BR,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 24000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Al+Waab+Garden+Villas+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-039-wgv-v03',
    serviceCharges: 1800,
    depositAmount: 72000,
    agencyFee: 14400,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AW-0501',
    legalDuration: '2 Years',
    maintenanceNotes: 'Private garden freshly landscaped. Irrigation system new. Pool serviced Oct 2024.',
    accessLockbox: 'Code: 3344 — Waab Gardens Gate A, Villa 3',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-039-v1'],
    listedDate: '2024-10-15',
    lastUpdated: '2024-11-22',
  },
  {
    id: 'PRV-040',
    realtorMOCI: 'PRV-MOCI-2024-0502',
    property: 'Al Waab Garden Villas',
    unitNo: 'WGV-V09',
    zone: 'Al Waab',
    type: UnitType.Villa,
    subType: SubType.Villa_3BR,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 18500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Waab+Garden+Villas+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-040-wgv-v09',
    serviceCharges: 1380,
    depositAmount: 55500,
    agencyFee: 11100,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AW-0502',
    legalDuration: '2 Years',
    maintenanceNotes: 'Long-term tenancy. Annual maintenance completed Jul 2024.',
    accessLockbox: 'Code: 6691 — Waab Gardens Gate A, Villa 9',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-040-v1'],
    listedDate: '2024-01-05',
    lastUpdated: '2024-07-20',
  },
  {
    id: 'PRV-041',
    realtorMOCI: 'PRV-MOCI-2024-0503',
    property: 'Green Hills Compound',
    unitNo: 'GHC-V04',
    zone: 'Al Waab',
    type: UnitType.Villa,
    subType: SubType.Villa_5BR,
    furnishing: Furnishing.Unfurnished,
    listingType: ListingType.Rent,
    rent: 32000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Green+Hills+Compound+Al+Waab+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-041-ghc-v04',
    serviceCharges: 2400,
    depositAmount: 96000,
    agencyFee: 19200,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AW-0503',
    legalDuration: '2 Years (Negotiable)',
    maintenanceNotes: 'Flagship 5BR compound villa. Private pool, gym, majlis. No defects. Corporate preferred.',
    accessLockbox: 'Code: 8852 — Green Hills Main Gate, Villa 4',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-041-v1', 'https://drive.google.com/file/d/prv-hist-041-v2'],
    listedDate: '2024-09-10',
    lastUpdated: '2024-11-18',
  },
  {
    id: 'PRV-042',
    realtorMOCI: 'PRV-MOCI-2024-0504',
    property: 'Green Hills Compound',
    unitNo: 'GHC-A12',
    zone: 'Al Waab',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 10500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Green+Hills+Compound+Al+Waab+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-042-ghc-a12',
    serviceCharges: 780,
    depositAmount: 21000,
    agencyFee: 6300,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AW-0504',
    legalDuration: '1 Year',
    maintenanceNotes: 'Attached apartment to compound. Under active lease. Shared amenity access included.',
    accessLockbox: 'Code: 1129 — Green Hills Annex Block A, Unit 12',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-042-v1'],
    listedDate: '2024-03-15',
    lastUpdated: '2024-09-20',
  },
  {
    id: 'PRV-043',
    realtorMOCI: 'PRV-MOCI-2024-0505',
    property: 'Waab Square Tower',
    unitNo: 'WST-07-02B',
    zone: 'Al Waab',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 7000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Waab+Square+Tower+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-043-wst-07-02b',
    serviceCharges: 530,
    depositAmount: 14000,
    agencyFee: 4200,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-AW-0505',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Bright corner unit. New AC split units installed. Ready immediately.',
    accessLockbox: 'Code: 4418 — WST Level 7, Unit 2B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-043-v1'],
    listedDate: '2024-11-16',
    lastUpdated: '2024-11-30',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: MSHEIREB DOWNTOWN DOHA — 5 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-044',
    realtorMOCI: 'PRV-MOCI-2024-0601',
    property: 'Heritage House Msheireb',
    unitNo: 'HHM-04-02A',
    zone: 'Msheireb Downtown',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 13500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Msheireb+Downtown+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-044-hhm-04-02a',
    serviceCharges: 1010,
    depositAmount: 27000,
    agencyFee: 8100,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-MD-0601',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Heritage-style modern unit. Smart building management. Zero defects on last inspection.',
    accessLockbox: 'Code: 6650 — Heritage House Block 4, Level 2',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-044-v1'],
    listedDate: '2024-10-18',
    lastUpdated: '2024-11-25',
  },
  {
    id: 'PRV-045',
    realtorMOCI: 'PRV-MOCI-2024-0602',
    property: 'Heritage House Msheireb',
    unitNo: 'HHM-11-05C',
    zone: 'Msheireb Downtown',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 19000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Msheireb+Downtown+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-045-hhm-11-05c',
    serviceCharges: 1430,
    depositAmount: 38000,
    agencyFee: 11400,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-MD-0602',
    legalDuration: '2 Years',
    maintenanceNotes: 'Occupied by senior diplomat. No maintenance requests. Quarterly checks maintained.',
    accessLockbox: 'Code: 9931 — Heritage House Block 11, Level 5',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-045-v1'],
    listedDate: '2024-02-10',
    lastUpdated: '2024-08-30',
  },
  {
    id: 'PRV-046',
    realtorMOCI: 'PRV-MOCI-2024-0603',
    property: 'Downtown Msheireb Tower',
    unitNo: 'DMT-06-03B',
    zone: 'Msheireb Downtown',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 9000,
    status: Status.Under_Maintenance,
    locationMapUrl: 'https://maps.google.com/?q=Msheireb+Downtown+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-046-dmt-06-03b',
    serviceCharges: 680,
    depositAmount: 18000,
    agencyFee: 5400,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-MD-0603',
    legalDuration: '1 Year',
    maintenanceNotes: 'Lift shaft vibration investigation ongoing per building management. Cosmetic wall repair in progress. ETA: Dec 22, 2024.',
    accessLockbox: 'Code: 2267 — DMT Level 6, Unit 3B (Contractor)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-046-v1'],
    listedDate: '2024-07-20',
    lastUpdated: '2024-11-28',
  },
  {
    id: 'PRV-047',
    realtorMOCI: 'PRV-MOCI-2024-0604',
    property: 'Downtown Msheireb Tower',
    unitNo: 'DMT-15-07A',
    zone: 'Msheireb Downtown',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 14000,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Msheireb+Downtown+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-047-dmt-15-07a',
    serviceCharges: 1050,
    depositAmount: 28000,
    agencyFee: 8400,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-MD-0604',
    legalDuration: '1 Year',
    maintenanceNotes: 'Reserved for incoming exec transfer. Snagging complete. Premium finishing throughout.',
    accessLockbox: 'Code: 5541 — DMT Level 15, Suite 7A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-047-v1'],
    listedDate: '2024-11-01',
    lastUpdated: '2024-11-27',
  },
  {
    id: 'PRV-048',
    realtorMOCI: 'PRV-MOCI-2024-0605',
    property: 'Msheireb Executive Suites',
    unitNo: 'MES-03-01C',
    zone: 'Msheireb Downtown',
    type: UnitType.Studio,
    subType: SubType.Studio,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 6000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Msheireb+Downtown+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-048-mes-03-01c',
    serviceCharges: 390,
    depositAmount: 12000,
    agencyFee: 3600,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-MD-0605',
    legalDuration: '6 Months (Renewable)',
    maintenanceNotes: 'Serviced suite. Housekeeping included in service charge. No defects.',
    accessLockbox: 'Code: 7780 — Executive Suites Level 3, Studio 1C',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-048-v1'],
    listedDate: '2024-11-10',
    lastUpdated: '2024-11-29',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: AL DAFNA — 4 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-049',
    realtorMOCI: 'PRV-MOCI-2024-0701',
    property: 'Dafna Business Suites',
    unitNo: 'DBS-08-04A',
    zone: 'Al Dafna',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 11500,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Dafna+Business+Suites+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-049-dbs-08-04a',
    serviceCharges: 860,
    depositAmount: 23000,
    agencyFee: 6900,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-DF-0701',
    legalDuration: '1 Year',
    maintenanceNotes: 'Business professional tenant. No issues. Last inspection: Sept 2024.',
    accessLockbox: 'Code: 1144 — DBS Level 8, Suite 4A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-049-v1'],
    listedDate: '2024-03-25',
    lastUpdated: '2024-09-25',
  },
  {
    id: 'PRV-050',
    realtorMOCI: 'PRV-MOCI-2024-0702',
    property: 'Dafna Business Suites',
    unitNo: 'DBS-18-08B',
    zone: 'Al Dafna',
    type: UnitType.Apartment,
    subType: SubType.BHK_1,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 8000,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Al+Dafna+Business+Suites+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-050-dbs-18-08b',
    serviceCharges: 610,
    depositAmount: 16000,
    agencyFee: 4800,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-DF-0702',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'High-floor unit with city view. Just vacated and cleared. No open tickets.',
    accessLockbox: 'Code: 8816 — DBS Level 18, Unit 8B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-050-v1'],
    listedDate: '2024-11-18',
    lastUpdated: '2024-11-30',
  },
  {
    id: 'PRV-051',
    realtorMOCI: 'PRV-MOCI-2024-0703',
    property: 'Al Dafna Tower Residences',
    unitNo: 'DTR-12-05A',
    zone: 'Al Dafna',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 12000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Al+Dafna+Tower+Residences+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-051-dtr-12-05a',
    serviceCharges: 900,
    depositAmount: 24000,
    agencyFee: 7200,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-DF-0703',
    legalDuration: '1 Year',
    maintenanceNotes: 'Active lease. Long-term tenant. No issues reported in 2024.',
    accessLockbox: 'Code: 3377 — DTR Level 12, Apt 5A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-051-v1'],
    listedDate: '2024-02-15',
    lastUpdated: '2024-08-10',
  },
  {
    id: 'PRV-052',
    realtorMOCI: 'PRV-MOCI-2024-0704',
    property: 'Al Dafna Tower Residences',
    unitNo: 'DTR-22-09C',
    zone: 'Al Dafna',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 16500,
    status: Status.Under_Maintenance,
    locationMapUrl: 'https://maps.google.com/?q=Al+Dafna+Tower+Residences+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-052-dtr-22-09c',
    serviceCharges: 1240,
    depositAmount: 33000,
    agencyFee: 9900,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-DF-0704',
    legalDuration: '1 Year',
    maintenanceNotes: 'Ceiling leak from floor above addressed. Remediation work Dec 2024. Compensation discussion with previous tenant ongoing.',
    accessLockbox: 'Code: 6672 — DTR Level 22, Unit 9C (Contractor)',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-052-v1', 'https://drive.google.com/file/d/prv-hist-052-v2'],
    listedDate: '2024-08-01',
    lastUpdated: '2024-11-27',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ZONE: MADINAT KHALIFA — 3 units
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'PRV-053',
    realtorMOCI: 'PRV-MOCI-2024-0801',
    property: 'Khalifa Crown Tower',
    unitNo: 'KCT-09-04B',
    zone: 'Madinat Khalifa',
    type: UnitType.Apartment,
    subType: SubType.BHK_2,
    furnishing: Furnishing.Semi_Furnished,
    listingType: ListingType.Rent,
    rent: 10500,
    status: Status.Available,
    locationMapUrl: 'https://maps.google.com/?q=Madinat+Khalifa+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-053-kct-09-04b',
    serviceCharges: 790,
    depositAmount: 21000,
    agencyFee: 6300,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-MK-0801',
    legalDuration: '1 Year (Renewable)',
    maintenanceNotes: 'Quiet residential location. No open maintenance tickets. Parking space allocated.',
    accessLockbox: 'Code: 4480 — KCT Level 9, Unit 4B',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-053-v1'],
    listedDate: '2024-11-03',
    lastUpdated: '2024-11-26',
  },
  {
    id: 'PRV-054',
    realtorMOCI: 'PRV-MOCI-2024-0802',
    property: 'Khalifa Crown Tower',
    unitNo: 'KCT-21-08A',
    zone: 'Madinat Khalifa',
    type: UnitType.Apartment,
    subType: SubType.BHK_3,
    furnishing: Furnishing.Fully_Furnished,
    listingType: ListingType.Rent,
    rent: 15000,
    status: Status.Leased,
    locationMapUrl: 'https://maps.google.com/?q=Madinat+Khalifa+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-054-kct-21-08a',
    serviceCharges: 1130,
    depositAmount: 30000,
    agencyFee: 9000,
    agencyFeePercentage: 5,
    mociContractStatus: 'REGISTERED',
    mociContractNumber: 'MOCI-2024-MK-0802',
    legalDuration: '2 Years',
    maintenanceNotes: 'Long-term family tenant. Annual service completed Q2 2024. No issues.',
    accessLockbox: 'Code: 7715 — KCT Level 21, Suite 8A',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-054-v1'],
    listedDate: '2024-01-25',
    lastUpdated: '2024-07-15',
  },
  {
    id: 'PRV-055',
    realtorMOCI: 'PRV-MOCI-2024-0803',
    property: 'Garden View Khalifa',
    unitNo: 'GVK-V02',
    zone: 'Madinat Khalifa',
    type: UnitType.Villa,
    subType: SubType.Villa_4BR,
    furnishing: Furnishing.Unfurnished,
    listingType: ListingType.Rent,
    rent: 26000,
    status: Status.Reserved,
    locationMapUrl: 'https://maps.google.com/?q=Madinat+Khalifa+Doha+Qatar',
    mediaUrl: 'https://drive.google.com/drive/folders/prv-055-gvk-v02',
    serviceCharges: 1950,
    depositAmount: 78000,
    agencyFee: 15600,
    agencyFeePercentage: 5,
    mociContractStatus: 'PENDING',
    mociContractNumber: 'MOCI-2024-MK-0803',
    legalDuration: '2 Years',
    maintenanceNotes: 'Premium compound villa with garden. Reserved pending final contract signatures.',
    accessLockbox: 'Code: 3325 — Garden View Compound Gate, Villa 2',
    assetHistoryLinks: ['https://drive.google.com/file/d/prv-hist-055-v1'],
    listedDate: '2024-10-08',
    lastUpdated: '2024-11-29',
  },
];
