-- Populate alias_zone_tags for every zone in cr_zone_codes.
-- ON CONFLICT DO NOTHING preserves the 15 zones already seeded in 20260806_alias_architecture.sql.
INSERT INTO public.alias_zone_tags (zone_code, zone_tag, zone_label) VALUES
  (1,  'AJ', 'Al Jasrah'),
  (2,  'BD', 'Al Bidda'),
  (3,  'FM', 'Fereej Bin Jassim'),
  (4,  'MB', 'Musheireb'),
  (5,  'NJ', 'Al Najada'),
  (6,  'OG', 'Old Al Ghanim'),
  (7,  'SQ', 'Al Souq'),
  (10, 'WS', 'Wadi Al Sail'),
  (11, 'RL', 'Rumeilah'),
  (12, 'BD', 'Al Bidda'),
  (13, 'MB', 'Musheireb'),
  (14, 'FA', 'Fereej Abdel Aziz'),
  (15, 'DJ', 'Doha Al Jadeeda'),
  (16, 'OG', 'Old Al Ghanim'),
  (17, 'OH', 'Old Al Hitmi'),
  (18, 'SM', 'As Salatah'),
  (19, 'DP', 'Doha Port'),
  (20, 'WS', 'Wadi Al Sail'),
  (21, 'RL', 'Rumeilah'),
  (22, 'BM', 'Fereej Bin Mahmoud'),
  (23, 'BM', 'Fereej Bin Mahmoud'),
  (24, 'RK', 'Rawdat Al Khail'),
  (25, 'MA', 'Al Mansoura'),
  (26, 'NM', 'Najma'),
  (27, 'UG', 'Umm Ghuwailina'),
  (28, 'RA', 'Ras Abu Aboud'),
  (30, 'DH', 'Duhail'),
  (31, 'UL', 'Umm Lekhba'),
  (32, 'MN', 'Madinat Khalifa North'),
  (33, 'AM', 'Al Markhiya'),
  (34, 'MS', 'Madinat Khalifa South'),
  (35, 'FK', 'Fereej Kulaib'),
  (36, 'ME', 'Al Messila'),
  (37, 'BO', 'Bin Omran'),
  (38, 'AS', 'Al Sadd'),
  (39, 'SA', 'New Al Mirqab'),
  (40, 'NS', 'New Salata'),
  (41, 'NU', 'Nuaija'),
  (42, 'HL', 'Al Hilal'),
  (43, 'NU', 'Nuaija'),
  (44, 'NU', 'Nuaija'),
  (45, 'OA', 'Old Airport'),
  (46, 'TH', 'Al Thumama'),
  (47, 'TH', 'Al Thumama'),
  (48, 'DA', 'Doha Airport'),
  (49, 'AA', 'Airport Area'),
  (50, 'Z5', 'Zone 50'),
  (51, 'AH', 'Abu Hamour'),
  (52, 'MH', 'Muaither'),
  (53, 'AW', 'Al Waab'),
  (54, 'RJ', 'Al Rayyan Al Jadeed'),
  (55, 'FE', 'Fereej Al Amir'),
  (56, 'AK', 'Ain Khaled'),
  (57, 'IA', 'Industrial Area'),
  (58, 'Z8', 'Zone 58'),
  (60, 'DF', 'Al Dafna'),
  (61, 'WB', 'West Bay'),
  (63, 'ON', 'Onaiza'),
  (64, 'LB', 'Lejbailat'),
  (65, 'ON', 'Onaiza'),
  (66, 'LQ', 'Legtaifiya'),
  (67, 'HM', 'Hazm Al Markhiya'),
  (68, 'JL', 'Jelaiah'),
  (69, 'LS', 'Lusail'),
  (70, 'UQ', 'Umm Qarn'),
  (71, 'US', 'Umm Salal'),
  (72, 'SN', 'Al Shahaniya'),
  (73, 'DK', 'Dukhan'),
  (74, 'KH', 'Al Khor'),
  (75, 'TK', 'Al Thakhira'),
  (76, 'RF', 'Ras Laffan'),
  (77, 'SH', 'Al Shamal'),
  (78, 'RW', 'Ar Ruwais'),
  (79, 'ZU', 'Al Zubarah'),
  (80, 'JM', 'Al Jemailiya'),
  (81, 'GR', 'Gharrafat Al Rayyan'),
  (82, 'RR', 'Rawdat Rashed'),
  (83, 'BH', 'Bani Hajer'),
  (84, 'MK', 'Mukaynis'),
  (85, 'UB', 'Umm Bab'),
  (86, 'RE', 'Remote Western Areas'),
  (90, 'WK', 'Al Wakrah'),
  (91, 'WU', 'Al Wukair'),
  (92, 'MC', 'Mesaieed'),
  (93, 'SL', 'Sealine'),
  (94, 'KA', 'Al Karaana'),
  (95, 'AD', 'Al Adaid'),
  (96, 'SR', 'Abu Samra'),
  (97, 'UR', 'Umm Bab Remote'),
  (98, 'ND', 'New Development Areas')
ON CONFLICT (zone_code) DO NOTHING;
